/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.coldraincn.libs.*;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
      
        StdOut.println("ssss");
    }
}
